#!/usr/bin/env sh

deno check
deno lint
deno fmt --check
deno publish --allow-dirty --dry-run

cargo fmt -- --check
cargo clippy --no-deps -- -D warnings
# cargo test # we skip this cuz cargo test generate files

deno task build:rs