name: Continuous Integration

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
  workflow_call:

jobs:
  rust-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: rustup override set nightly
      - run: rustup --version
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Linter
        run: |-
          rustup component add rustfmt
          cargo fmt -- --check

      - name: Clippy
        run: |-
          rustup component add clippy
          cargo clippy --locked --no-deps -- -D warnings

      - name: Test
        run: cargo test --locked --verbose

  js-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      # - run: deno check we don't do check here cuz it needs compile the rust code in ts first
      - run: deno fmt --check
      - run: deno lint
